version: '3.4'

services:
  lojavirtual:
    image: ${DOCKER_REGISTRY-}lojavirtual
    build:
      context: .
      dockerfile: LojaVirtual/Dockerfile
    ports:
    - "37009:80"
    - "36009:443"
    networks:
      default:
        ipv4_address: "172.28.1.8"
volumes:
  db_postgre:
networks:  
    default:
        external:  
            name: custom-network
