version: "3.6"
services:
  dbpost:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_postgre:/var/lib/postgresql/datavolumes
    networks:
      wp-net:      
volumes:
  db_postgre:
networks:
  wp-net:
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    name: estudo
    ipam:
      driver: default
